version: '2.1'

services:
  ia-case-notifications-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/ia-case-notifications-api
    container_name: ia-case-notifications-api
    environment:
      - JAVA_OPTS
      # these environment variables are used by java-logging library
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_APPENDER
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - S2S_URL:http://service-auth-provider-api:4502
    ports:
      - ${SERVER_PORT:-8093}:${SERVER_PORT:-8093}
