version: '3'

services:
  ia-case-notifications-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    networks:
      - compose_default
    image: hmcts/ia-case-notifications-api
    container_name: ia-case-notifications-api
    environment:
      JAVA_OPTS:
      # these environment variables are used by java-logging library
      JSON_CONSOLE_PRETTY_PRINT:
      ROOT_APPENDER:
      ROOT_LOGGING_LEVEL:
      REFORM_SERVICE_TYPE:
      REFORM_SERVICE_NAME:
      REFORM_TEAM:
      REFORM_ENVIRONMENT:
      LOGBACK_DATE_FORMAT:
      LOGBACK_REQUIRE_THREAD:
      LOGBACK_REQUIRE_ALERT_LEVEL: "false"
      LOGBACK_REQUIRE_ERROR_CODE: "false"
      # Application environment variables
      S2S_URL: http://service-auth-provider-api:8080
      IA_IDAM_REDIRECT_URI: http://idam-api
      IDAM_URL: http://idam-api:8080
      CCD_URL: http://ccd-data-store-api:4452
      CCD_GW_URL: http://ccd-api-gateway-web:3453
      DM_URL: http://dm-store:8080
      IA_IDAM_CLIENT_ID:
      IA_IDAM_SECRET:
      IA_S2S_MICROSERVICE:
      IA_S2S_SECRET:
      IA_SYSTEM_USERNAME:
      IA_SYSTEM_PASSWORD:
      IA_GOV_NOTIFY_KEY:
      IA_BAIL_GOV_NOTIFY_KEY:
      IA_RESPONDENT_EVIDENCE_DIRECTION_EMAIL:
      IA_RESPONDENT_NON_STANDARD_DIRECTION_UNTIL_LISTING_EMAIL:
      IA_RESPONDENT_REVIEW_DIRECTION_EMAIL:
    external_links:
      - idam-api
      - dm-store
      - service-auth-provider-api
      - ccd-data-store-api
    ports:
      - ${SERVER_PORT:-8093}:${SERVER_PORT:-8093}
networks:
  compose_default:
    external: true
