server:
  port: ${PORT:8093}

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: "/"

spring:
  application:
    name: Immigration & Asylum case notifications API
  jackson.date-format: yyyy-MM-dd
  main:
    allow-bean-definition-overriding: true

govnotify.key: ${IA_GOV_NOTIFY_KEY}
govnotify.template.responseReviewDirection: e3e36c28-b16a-4e85-b8e1-dbb7f6771181
govnotify.template.buildCaseDirection: 13a6331e-b0f5-4e64-ae1b-dc2c2fd0aeeb
govnotify.template.appealSubmittedCaseOfficer: 23769f75-673c-4682-8433-d751e540e730
govnotify.template.respondentEvidenceDirection: a1fee4a6-6650-4d91-8f9e-cd15944adef4
govnotify.template.legalRepresentativeReviewDirection: 75c6c191-083d-43a4-8811-f201fc4750a8
govnotify.template.respondentNonStandardDirection: 2e0dd0af-12d2-4a37-9bd1-dabdda1959bf
govnotify.template.respondentReviewDirection: a0e0018c-44ef-4a77-a9d5-c036faad29a1
govnotify.template.legalRepresentativeHearingRequirementsDirection: e6694559-38be-46a5-9894-9498b047e2c6
govnotify.template.caseOfficerSubmitCase: f6c5ad6b-d585-4421-a93f-c36126f3c4ce
govnotify.template.caseOfficerCaseListed: 58eab057-b5c0-4a69-8f71-a21d6f02da3d
govnotify.template.legalRepresentativeCaseListed: b87a1e5b-eec7-4268-a326-059893ab5c28
govnotify.template.homeOfficeCaseListed: 86936ac9-e8d0-4a4c-8169-0948d7fb7935
govnotify.template.caseOfficerCaseEdited: 5fdb27ee-dbd6-4aad-845c-d0a2db474a76
govnotify.template.endAppealHomeOfficeTemplateId: 993c1294-c6b8-4b46-ab0f-ab01b4f6607b
govnotify.template.appealOutcomeAllowedHomeOfficeTemplateId: ba4f360b-586b-433d-b5c2-ceb0f2f5a323
govnotify.template.appealOutcomeAllowedLegalRepresentativeTemplateId: 95fa02b7-babb-444d-805c-06dff42cfea7
govnotify.template.appealOutcomeDismissedHomeOfficeTemplateId: ac808545-4e6f-4e87-975b-14d10a929233
govnotify.template.appealOutcomeDismissedLegalRepresentativeTemplateId: 811b5eba-b53d-4fa1-baa0-5f9f3d1ba68f
govnotify.template.endAppealLegalRepresentativeTemplateId: 44ae9e7a-adeb-4d78-b2ed-219f4390b166
govnotify.template.recordRefusedApplicationLegalRepresentativeTemplateId: 46778cba-1db5-4f17-9437-3b2944274df2
govnotify.template.recordRefusedApplicationHomeOfficeTemplateId: 911d4121-1300-4c52-b8b3-bfa7526ca74d
govnotify.template.respondentEvidenceSubmittedTemplateId: b71b11f6-c485-45a2-a162-c2310a094821
govnotify.template.legalRepresentativeBuildCaseDirection: ea1a6d4c-0d6e-4d95-afb7-07ddcebaecbd
govnotify.template.hearingBundleReadyLegalRepTemplateId: 03d427d1-f032-40cb-8e8e-96ea54c2f234
govnotify.template.hearingBundleReadyHomeOfficeTemplateId: d4c6352d-325a-4933-91bb-61eb56554efc
govnotify.template.homeOfficeResponseUploadedTemplateId: 32584965-8374-469a-a71b-b417da7709ed
govnotify.template.legalRepresentativeCaseEditedTemplateId: 347f2959-4cb5-447f-bd35-cb1e2308f6fb
govnotify.template.homeOfficeCaseEditedTemplateId: 54975c09-6634-4f1a-bfe6-caaeb5913e6a
govnotify.template.legalRepresentativeNonStandardDirectionTemplateId: d85587f4-2a7d-44a2-b6d8-538b91b7144b
govnotify.template.legalRepNonStandardDirectionOfHomeOfficeTemplateId: a03720df-2c7d-403d-9a45-a58c192e8570
govnotify.template.reviewHearingRequirementsAdminOfficerTemplateId: 58632d37-fe36-4fae-adfd-b44bf8509770
govnotify.template.withoutHearingRequirementsAdminOfficerTemplateId: 435ea40a-47ac-4397-9bd8-37be50589162
govnotify.template.caseOfficerRequestHearingRequirementsTemplateId: f6185789-8328-4208-8ee5-8a12d641180f
govnotify.template.submittedHearingRequirementsLegalRepTemplateId: bfee0880-9bdd-41a1-805a-8be4818bbb6a
govnotify.template.submittedHearingRequirementsCaseOfficerTemplateId: aa36afd2-254b-4fd7-b7c8-72078176294f
govnotify.template.uploadedAdditionalEvidenceTemplateId: b012e823-c658-4d10-a7a5-95e54f73dba8

govnotify.template.appealSubmittedAppellant.email: b53d6e97-b7d9-4112-9669-9db81e563506
govnotify.template.appealSubmittedAppellant.sms: 2cc4d346-cfb6-4ea9-93b3-c3f1f4f56491
govnotify.template.appealSubmittedOutOfTimeAppellant.email: 98f18bbb-c746-4fbd-8860-a629957a94ac
govnotify.template.appealSubmittedOutOfTimeAppellant.sms: 2587432c-aeb9-483d-bc0d-086b175f4fa7

govnotify.baseUrl: "https://api.notifications.service.gov.uk"

notificationSender.deduplicateSendsWithinSeconds: 60
iaCcdFrontendUrl: ${IA_CCD_FRONTEND_URL:http://localhost:3451/}

iaAipFrontendUrl: ${IA_AIP_FRONTEND_URL:https://localhost:3000/}

tsvStringsFileLocation: strings.tsv

ia_system_user: ${IA_SYSTEM_USERNAME:system-user}
ia_system_user_password: ${IA_SYSTEM_PASSWORD:system-password}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
  authorisedServices:
    - "ccd"
    - "ccd_data"
    - "ccd_gw"
    - "ccd_ps"
    - "iac"
  authorisedRoles:
    - "caseworker-ia"
    - "citizen"
  roleEventAccess:
    citizen:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
    caseworker-ia-legalrep-solicitor:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
      - "buildCase"
      - "submitCase"
      - "uploadAdditionalEvidence"
      - "draftHearingRequirements"
      - "requestHearingRequirementsFeature"
    caseworker-ia-caseofficer:
      - "sendDirection"
      - "changeDirectionDueDate"
      - "requestCaseEdit"
      - "requestHearingRequirements"
      - "reviewHearingRequirements"
      - "listCaseWithoutHearingRequirements"
      - "requestHearingRequirementsFeature"
      - "draftHearingRequirements"
      - "requestRespondentEvidence"
      - "uploadRespondentEvidence"
      - "requestRespondentReview"
      - "addAppealResponse"
      - "createCaseSummary"
      - "generateHearingBundle"
      - "editCaseListing"
      - "endAppeal"
      - "recordApplication"
      - "requestCaseBuilding"
      - "requestResponseReview"
      - "sendDecisionAndReasons"
    caseworker-ia-admofficer:
      - "listCase"
      - "editCaseListing"
    caseworker-ia-homeofficeapc:
      - "uploadHomeOfficeBundle"
      - "uploadAdditionalEvidenceHomeOffice"
    caseworker-ia-homeofficelart:
      - "uploadHomeOfficeAppealResponse"
      - "uploadAdditionalEvidenceHomeOffice"
    caseworker-ia-homeofficepou:
      - "uploadAdditionalEvidenceHomeOffice"
    caseworker-ia-respondentofficer:
      - "uploadHomeOfficeBundle"
      - "addAppealResponse"
      - "uploadHomeOfficeAppealResponse"
      - "uploadAdditionalEvidenceHomeOffice"

### dependency configuration
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:4501}
auth.idam.client.detailsUri: "/o/userinfo"
auth.idam.client.jwkUri: "/o/jwks"
auth.idam.client.id: ${IA_IDAM_CLIENT_ID:ia}
auth.idam.client.secret: ${IA_IDAM_SECRET:something}
auth.idam.client.redirectUri: ${IA_IDAM_REDIRECT_URI:http://localhost}
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
core_case_data_api_url: ${CCD_URL:http://127.0.0.1:4452}
document_management.url: ${DM_URL:http://127.0.0.1:4506}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:ia}
idam.s2s-auth.url: ${S2S_URL:http://127.0.0.1:4502}

### Email addresses
hearingCentreEmailAddresses:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_EMAIL:hc-bradford@example.com}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_EMAIL:hc-manchester@example.com}
  newport: ${IA_HEARING_CENTRE_NEWPORT_EMAIL:hc-newport@example.com}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_EMAIL:hc-taylorhouse@example.com}
  northShields: ${IA_HEARING_CENTRE_NORTH_SHIELDS_EMAIL:hc-north-shields@example.com}
  birmingham: ${IA_HEARING_CENTRE_BIRMINGHAM_EMAIL:hc-birmingham@example.com}
  hattonCross: ${IA_HEARING_CENTRE_HATTON_CROSS_EMAIL:hc-hatton-cross@example.com}
  glasgow: ${IA_HEARING_CENTRE_GLASGOW_EMAIL:hc-glasgow@example.com}

homeOfficeEmailAddresses:
  bradford: ${IA_HOME_OFFICE_BRADFORD_EMAIL:ho-bradford@example.com}
  manchester: ${IA_HOME_OFFICE_MANCHESTER_EMAIL:ho-manchester@example.com}
  newport: ${IA_HOME_OFFICE_NEWPORT_EMAIL:ho-newport@example.com}
  taylorHouse: ${IA_HOME_OFFICE_TAYLOR_HOUSE_EMAIL:ho-taylorhouse@example.com}
  northShields: ${IA_HOME_OFFICE_NORTH_SHIELDS_EMAIL:ho-north-shields@example.com}
  birmingham: ${IA_HOME_OFFICE_BIRMINGHAM_EMAIL:ho-birmingham@example.com}
  hattonCross: ${IA_HOME_OFFICE_HATTON_CROSS_EMAIL:ho-hatton-cross@example.com}
  glasgow: ${IA_HOME_OFFICE_GLASGOW_EMAIL:ho-glasgow@example.com}

hearingCentreTelephoneNumber:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_TELEPHONE:0300 123 1711}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_TELEPHONE:0300 123 1711}
  newport: ${IA_HEARING_CENTRE_NEWPORT_TELEPHONE:0300 123 1711}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_TELEPHONE:0300 123 1711}
  northShields: ${IA_HEARING_CENTRE_NORTH_SHIELDS_TELEPHONE:0300 123 1711}
  birmingham: ${IA_HEARING_CENTRE_BIRMINGHAM_TELEPHONE:0300 123 1711}
  hattonCross: ${IA_HEARING_CENTRE_HATTON_CROSS_TELEPHONE:0300 123 1711}
  glasgow: ${IA_HEARING_CENTRE_GLASGOW_TELEPHONE:0300 123 1711}

endAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_END_APPEAL_EMAIL:ho-end-appeal@example.com}
allowedAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_ALLOWED_APPEAL_EMAIL:ho-allowed-appeal@example.com}
dismissedAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_DISMISSED_APPEAL_EMAIL:ho-dismissed-appeal@example.com}

reviewHearingRequirementsAdminOfficerEmailAddress: ${IA_ADMIN_OFFICER_REVIEW_HEARING_REQUIREMENTS_EMAIL:ao-review@example.com}

respondentEmailAddresses:
  nonStandardDirectionUntilListing: ${IA_RESPONDENT_NON_STANDARD_DIRECTION_UNTIL_LISTING_EMAIL:respondent@example.com}
  respondentEvidenceDirection: ${IA_RESPONDENT_EVIDENCE_DIRECTION_EMAIL:respondent@example.com}
  respondentReviewDirection: ${IA_RESPONDENT_REVIEW_DIRECTION_EMAIL:respondent-lart@example.com}
