server:
  port: ${PORT:8093}

management:
  endpoint:
    health:
      show-details: "always"
    status:
      http-mapping:
        UP: 200
        DOWN: 503
  endpoints:
    web:
      base-path: "/"

health:
  services:
    notificationService:
      uri: "https://status.notifications.service.gov.uk"
      response: '"status":"UP"'

spring:
  application:
    name: Immigration & Asylum case notifications API
  jackson.date-format: yyyy-MM-dd
  main:
    allow-bean-definition-overriding: true

govnotify:
  baseUrl: "https://api.notifications.service.gov.uk"
  key: ${IA_GOV_NOTIFY_KEY}
  template:
    forceCaseProgression:
      caseBuilding.to.caseUnderReview:
        legalRep:
          email: e8197293-3db9-4af9-95d2-067e217c03c2
    appealSubmitted:
      legalRep:
        paid:
          email: e767a7ab-adc7-4784-9542-547ebe717fa4
        paymentPending:
          email: 2ef16c77-144d-49b5-b720-b88bedf8bda1
      appellant:
        email: 4625616a-178b-45fb-aebf-8cb945369ae0
        sms: 5b7091e5-908a-4c5b-ac66-5dc5216fc53b
      caseOfficer:
        email: f90aa4d9-159d-4423-ab96-73a1e23c92d4
      homeOffice:
        email: 0f9c8b34-f9d2-4796-804a-a9cd0ab5359d
    appealSubmittedOutOfTime:
      appellant:
        email: b864d01f-c80c-4d91-947f-9599f0b64163
        sms: c52f3074-4b5a-47e0-8dec-154ac5fc0513
    pendingPayment:
      legalRep:
        paid:
          email: 91cf84fe-55f0-41a4-9d0f-fe13ae45fb8c
        paidAfterAppealSubmitted:
          beforeListing:
            email: da72f9c7-5654-40b3-b9e6-c474281b023e
          afterListing:
            email: 933df53d-5700-4ec5-8488-aa33b1541aaa
    requestRespondentEvidenceDirection:
      appellant:
        email: 9c8ab848-b1f7-4dbe-9854-4922e94ece67
        sms: e805b3c5-b1e2-4ad1-9416-3298ca765738
      legalRep:
        email: 33430912-89d5-416d-8d49-52eae9ce82c3
      respondent:
        email: 1e718009-b7f7-4d0a-976d-a411dae559fb
    respondentEvidenceSubmitted:
      caseOfficer:
        email: a1511860-2d05-42ff-8a08-778840424d83
    requestReasonsForAppeal:
      appellant:
        email: 50f1b88e-51d5-446c-b2da-1188feb7e26c
        sms: a7056fd8-6de7-408e-881b-c6f9984fe5cf
    submitReasonsForAppeal:
      appellant:
        email: cd10866a-094d-43aa-bdf5-1e20fda9b10d
        sms: d7b0ef96-ea54-46f1-a605-6e3855b09b91
      caseOfficer:
        email: 2e3d6dfb-409d-4b45-a50b-0703c47341ea
    responseReviewDirection:
      legalRep:
        email: 91d3e99c-ece1-4dd0-bc85-e416ff642b41
    buildCaseDirection:
      legalRep:
        email: b68e1cb2-ec92-488b-ad38-98a30f965419
    reviewDirection:
      legalRep:
        email: 091be655-72cd-49cb-a66c-2030f7437595
      respondent:
        email: 4d7dbe9b-f8e4-4508-a7d0-b7f4f1e26269
    nonStandardDirectionBeforeListing:
      respondent:
        email: 7a3b6e21-9296-4c9c-8644-782f7e4ee475
      legalRep:
        email: 2094dbc5-afa8-41bb-af4c-bbf8a520952e
    nonStandardDirectionAfterListing:
      respondent:
        email: 1780cfa2-965b-43bf-ac24-c964d36ebe4e
      legalRep:
        email: ea67076c-9da2-46d4-b0de-3e212846c8c8
    nonStandardDirectionOfHomeOfficeBeforeListing:
      legalRep:
        email: 22baf84c-e075-48a0-be94-7a25c522169d
    nonStandardDirectionOfHomeOfficeAfterListing:
      legalRep:
        email: 8ebc4642-8d0e-480c-bc13-05da4130a754
    hearingRequirementsDirection:
      legalRep:
        email: 2f3959b9-8c4b-400c-8ba3-459cd1056df7
    submitCase:
      caseOfficer:
        email: ceee3f8e-6657-4967-8066-4b0f40c4b4d4
    caseListed:
      caseOfficer:
        email: 38d28eca-f30e-4af3-b782-e30ef0e9d7ad
      homeOffice:
        email: 988c4d43-acea-4914-ac9a-b3ab04668dde
      legalRep:
        email: 67545160-0182-4510-96d0-ba39dbe63e5e
    caseEdited:
      caseOfficer:
        email: e634be28-0cdb-42b4-82b2-a60f37ef0294
      legalRep:
        email: 96c02198-771d-4bdc-890d-a69a063108b9
      homeOffice:
        email: df19f2db-dab9-454c-8d67-a11ead2f716f
    caseEditedNoChange:
      legalRep:
        email: 9bdfb1cb-c5a8-45b8-8f6c-b81d3d331db6
      homeOffice:
        email: 7adee5d3-b36b-4b19-becd-cb53b0edd251
    appealOutcomeAllowed:
      homeOffice:
        email: 0e8c3a70-4ba3-442b-8b12-235ee69a8d20
      legalRep:
        email: a5fc7b20-d69c-42ab-bd26-79c7cf9a7fda
    appealOutcomeDismissed:
      homeOffice:
        email: c59474ab-6074-49ec-b1ec-3ca1f1a45685
      legalRep:
        email: 3f89b2fa-0bbd-419e-b490-89ed27f63512
    endAppealBeforeListing:
      legalRep:
        email: 998bebf1-bb6c-44d6-a65b-ae7bb4ab186b
        nonPaymentEmail: b333bbd7-c675-4a77-87a8-9eba9d04ee6e
      homeOffice:
        email: 287f890a-47bc-41e1-a4a9-d143f8eecb9b
    endAppealAfterListing:
      legalRep:
        email: da6ca0ff-3955-498c-8d27-0eca1fbdf006
      homeOffice:
        email: 97b95f02-4dc3-4282-8c8c-802efb2d21ef
    recordRefusedApplicationBeforeListing:
      legalRep:
        email: 8bbb1537-9856-4a3e-b6cd-b862b1e192ff
      homeOffice:
        email: cf88047f-150a-4abc-a11d-a87a72985bf0
    recordRefusedApplicationAfterListing:
      legalRep:
        email: ee9f2f79-a2d6-42c8-a68c-1c66d9796623
      homeOffice:
        email: 5deb96c5-d5c5-4202-bcf1-425d4b0b1877
    requestCaseBuilding:
      legalRep:
        email: f1d15620-1781-4599-a3c1-d99ebb9616ac
    homeOfficeResponseUploaded:
      caseOfficer:
        email: f9813209-9f1f-43d4-b6f8-98e3f07645c3
    hearingBundleReady:
      legalRep:
        email: 4b8a8e0d-2901-411a-897c-dd2493bc8e03
      homeOffice:
        email: 3bb1f83d-4e4f-449d-a282-0ba2812cf88d
    requestHearingRequirements:
      legalRep:
        email: d86a45df-5c3d-41e6-9370-3b962d8711fa
    reviewHearingRequirements:
      adminOfficer:
        email: 62719354-7a95-4a5a-b42f-ae2223bd35ee
    withoutHearingRequirements:
      adminOfficer:
        email: 40983322-c1a5-4bb3-ba65-7307905c82a6
    submittedHearingRequirements:
      legalRep:
        email: 0c6dab6e-5c5d-4070-bccf-c8d490be7c19
      caseOfficer:
        email: 03aa193b-ba2c-4334-bbee-0b8244a91521
    uploadedAdditionalEvidenceBeforeListing:
      legalRep:
        email: c758ab41-4baa-4909-a6ba-31980395683a
      caseOfficer:
        email: 1ab1df2c-fbd7-4904-a2bb-325eeee05644
      homeOffice:
        email: b5e98804-54bf-43fb-ba3d-a033d0be99c3
    uploadedAdditionalEvidenceAfterListing:
      legalRep:
        email: 03abe2a5-5581-4bed-996a-6d19de352c4c
      caseOfficer:
        email: 8fff07bc-8f5c-4c3e-a8ce-1c7580dcc61e
      homeOffice:
        email: 5dadb06a-bf59-4d75-a8a0-84aa0f6bf24f
    uploadedAddendumEvidence:
      legalRep:
        email: 51dad728-a4d3-4ae8-9a4b-2f955b0d5b41
      caseOfficer:
        email: 61999628-3fb7-44de-a38c-304d6d765143
      homeOffice:
        email: 6e473679-dfc7-4fa7-96e3-583d0e8ff09f
    changeDirectionDueDate:
      legalRep:
        email: e8644a60-b943-438c-8ad0-ad7d947eeca1
      respondent:
        email: 9b383a96-3be7-4fb4-bbd0-39169b00a936
    changeDirectionDueDateOfHomeOffice:
      legalRep:
        email: e6a69f4d-48be-40ce-9c5f-10de47cd9dd3
    changeToHearingRequirements:
      adminOfficer:
        email: 95a45479-1a6e-413b-8d96-1ad1404ab3db
    removeAppealFromOnlineBeforeListing:
      homeOffice:
        email: 910ba1e7-00fc-4d4f-b4ba-2cbb91eeb3f7
      legalRep:
        email: 861f0327-6339-4c7e-8ef7-060532704122
    removeAppealFromOnlineAfterListing:
      homeOffice:
        email: 2e896da4-03c2-4474-b5b0-1a9fb31f33e5
      legalRep:
        email: 6de19b37-8f75-4388-8f22-56d9314569c6
    changeHearingCentre:
      legalRep:
        email: 4959d7cc-54f0-4cb4-b386-49940b89925e
      caseOfficer:
        email: 122b7fce-23c9-4b34-9055-8329264fd757
    applyForFtpa:
      respondent:
        email: 317498af-4da1-44c7-935e-d70009bc687f
      appellant:
        email: 28ea778a-f2fb-4447-9144-a3815c92edbc
      adminOfficer:
        email: aa44dab0-a9cd-4129-99bd-9ba2d4c8a57b
      otherLegalRep:
        email: 90630010-f2ed-4a97-a307-50291b017ed1
      otherHomeOffice:
        email: 9bcae84a-53e4-4971-a778-906506f49527
    respondentReview:
      legalRep:
        email: 8f028c03-60f3-4865-89df-ab6b66c82d74
    submitTimeExtension:
      appellant:
        email: eab37735-cba7-4b4b-96de-60ab33d96066
        sms: 9f0dce67-f8ef-46aa-a2a5-edb7fb19b6fd
      caseOfficer:
        email: 89540f93-a31b-4803-a83e-35cacd0c2415
    reviewTimeExtensionGranted:
      appellant:
        email: c445e51c-c41b-4bac-ba54-2fc576e5a100
        sms: d31c018c-ec16-410d-9a5d-6869044862f4
    reviewTimeExtensionRefused:
      appellant:
        email: 349fe4e3-1e71-4ddc-bf23-671d086a2204
        sms: 88117492-03e8-4c88-83b1-a172c114e354
    requestClarifyingQuestions:
      appellant:
        email: 500c6a6f-7d4f-4833-86c4-a07b43bbe717
        sms: bcfbd5a8-fc88-4c7f-ad16-e28d62dfbe73
    submitClarifyingQuestionAnswers:
      caseOfficer:
        email: 988461af-9111-4b4a-abba-6dfb3a40b422
      appellant:
        email: 6e439fce-aee0-45e8-97a5-4a79c9baac07
        sms: 9af78520-ffdb-4d08-b93f-3e6357fe0394
    requestCaseEdit:
      legalRep:
        email: 194e0a44-4fab-4e75-94a9-6d910dc4879a

notificationSender.deduplicateSendsWithinSeconds: 60

iaExUiFrontendUrl: ${IA_EXUI_FRONTEND_URL:https://manage-case.platform.hmcts.net/}
iaAipFrontendUrl: ${IA_AIP_FRONTEND_URL:https://localhost:3000/}

tsvStringsFileLocation: strings.tsv

ia_system_user: ${IA_SYSTEM_USERNAME:system-user}
ia_system_user_password: ${IA_SYSTEM_PASSWORD:system-password}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
  authorisedServices:
    - "ccd"
    - "ccd_data"
    - "ccd_gw"
    - "ccd_ps"
    - "iac"
  authorisedRoles:
    - "caseworker-ia"
    - "citizen"
  roleEventAccess:
    citizen:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
      - "submitReasonsForAppeal"
      - "submitTimeExtension"
      - "submitClarifyingQuestionAnswers"
    caseworker-ia-legalrep-solicitor:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
      - "makePayment"
      - "buildCase"
      - "submitCase"
      - "uploadAdditionalEvidence"
      - "draftHearingRequirements"
      - "requestHearingRequirementsFeature"
      - "uploadAddendumEvidenceLegalRep"
      - "applyForFTPAAppellant"
    caseworker-ia-caseofficer:
      - "sendDirection"
      - "changeDirectionDueDate"
      - "requestCaseEdit"
      - "requestHearingRequirements"
      - "reviewHearingRequirements"
      - "listCaseWithoutHearingRequirements"
      - "requestHearingRequirementsFeature"
      - "draftHearingRequirements"
      - "requestRespondentEvidence"
      - "uploadRespondentEvidence"
      - "requestRespondentReview"
      - "addAppealResponse"
      - "createCaseSummary"
      - "generateHearingBundle"
      - "editCaseListing"
      - "endAppeal"
      - "recordApplication"
      - "requestCaseBuilding"
      - "requestResponseReview"
      - "sendDecisionAndReasons"
      - "uploadAddendumEvidence"
      - "requestReasonsForAppeal"
      - "updateHearingAdjustments"
      - "removeAppealFromOnline"
      - "changeHearingCentre"
      - "reviewTimeExtension"
      - "sendDirectionWithQuestions"
      - "forceCaseToCaseUnderReview"
    caseworker-ia-admofficer:
      - "listCase"
      - "editCaseListing"
      - "sendDecisionAndReasons"
    caseworker-ia-homeofficeapc:
      - "uploadHomeOfficeBundle"
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
    caseworker-ia-homeofficelart:
      - "uploadHomeOfficeAppealResponse"
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
    caseworker-ia-homeofficepou:
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
      - "applyForFTPARespondent"
    caseworker-ia-respondentofficer:
      - "uploadHomeOfficeBundle"
      - "addAppealResponse"
      - "uploadHomeOfficeAppealResponse"
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
      - "applyForFTPARespondent"
    caseworker-ia-iacjudge:
      - "endAppeal"
      - "sendDecisionAndReasons"
      - "changeDirectionDueDate"
      - "sendDirection"
    caseworker-ia-system:
      - "requestHearingRequirementsFeature"

### dependency configuration
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:4501}
auth.idam.client.detailsUri: "/details"
auth.idam.client.id: ${IA_IDAM_CLIENT_ID:ia}
auth.idam.client.secret: ${IA_IDAM_SECRET:something}
auth.idam.client.redirectUri: ${IA_IDAM_REDIRECT_URI:http://localhost}
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
core_case_data_api_url: ${CCD_URL:http://127.0.0.1:4452}
document_management.url: ${DM_URL:http://127.0.0.1:4506}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:ia}
idam.s2s-auth.url: ${S2S_URL:http://127.0.0.1:4502}

### Email addresses
hearingCentreEmailAddresses:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_EMAIL:hc-bradford@example.com}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_EMAIL:hc-manchester@example.com}
  newport: ${IA_HEARING_CENTRE_NEWPORT_EMAIL:hc-newport@example.com}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_EMAIL:hc-taylorhouse@example.com}
  northShields: ${IA_HEARING_CENTRE_NORTH_SHIELDS_EMAIL:hc-north-shields@example.com}
  birmingham: ${IA_HEARING_CENTRE_BIRMINGHAM_EMAIL:hc-birmingham@example.com}
  hattonCross: ${IA_HEARING_CENTRE_HATTON_CROSS_EMAIL:hc-hatton-cross@example.com}
  glasgow: ${IA_HEARING_CENTRE_GLASGOW_EMAIL:hc-glasgow@example.com}

homeOfficeEmailAddresses:
  bradford: ${IA_HOME_OFFICE_BRADFORD_EMAIL:ho-bradford@example.com}
  manchester: ${IA_HOME_OFFICE_MANCHESTER_EMAIL:ho-manchester@example.com}
  newport: ${IA_HOME_OFFICE_NEWPORT_EMAIL:ho-newport@example.com}
  taylorHouse: ${IA_HOME_OFFICE_TAYLOR_HOUSE_EMAIL:ho-taylorhouse@example.com}
  northShields: ${IA_HOME_OFFICE_NORTH_SHIELDS_EMAIL:ho-north-shields@example.com}
  birmingham: ${IA_HOME_OFFICE_BIRMINGHAM_EMAIL:ho-birmingham@example.com}
  hattonCross: ${IA_HOME_OFFICE_HATTON_CROSS_EMAIL:ho-hatton-cross@example.com}
  glasgow: ${IA_HOME_OFFICE_GLASGOW_EMAIL:ho-glasgow@example.com}

hearingCentreTelephoneNumber:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_TELEPHONE:0300 123 1711}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_TELEPHONE:0300 123 1711}
  newport: ${IA_HEARING_CENTRE_NEWPORT_TELEPHONE:0300 123 1711}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_TELEPHONE:0300 123 1711}
  northShields: ${IA_HEARING_CENTRE_NORTH_SHIELDS_TELEPHONE:0300 123 1711}
  birmingham: ${IA_HEARING_CENTRE_BIRMINGHAM_TELEPHONE:0300 123 1711}
  hattonCross: ${IA_HEARING_CENTRE_HATTON_CROSS_TELEPHONE:0300 123 1711}
  glasgow: ${IA_HEARING_CENTRE_GLASGOW_TELEPHONE:0300 123 1711}

endAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_END_APPEAL_EMAIL:ho-end-appeal@example.com}
allowedAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_ALLOWED_APPEAL_EMAIL:ho-allowed-appeal@example.com}
dismissedAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_DISMISSED_APPEAL_EMAIL:ho-dismissed-appeal@example.com}

reviewHearingRequirementsAdminOfficerEmailAddress: ${IA_ADMIN_OFFICER_REVIEW_HEARING_REQUIREMENTS_EMAIL:ao-review@example.com}

respondentEmailAddresses:
  nonStandardDirectionUntilListing: ${IA_RESPONDENT_NON_STANDARD_DIRECTION_UNTIL_LISTING_EMAIL:respondent@example.com}
  respondentEvidenceDirection: ${IA_RESPONDENT_EVIDENCE_DIRECTION_EMAIL:respondent@example.com}
  respondentReviewDirection: ${IA_RESPONDENT_REVIEW_DIRECTION_EMAIL:respondent-lart@example.com}

ftpaSubmitted:
  ctscAdminEmailAddress: ${IA_CTSC_ADMIN_FTPA_SUBMITTED:ctscFtpaSubmitted@example.gov.uk}
  respondentEmailAddress: ${IA_RESPONDENT_FTPA_SUBMITTED:homeOfficeFtpaSubmitted@example.gov.uk}

customerServices:
  emailAddress: ${IA_CUSTOMER_SERVICES_EMAIL:contactia@justice.gov.uk}
  telephoneNumber: ${IA_CUSTOMER_SERVICES_TELEPHONE:0300 123 1711}

appellantDaysToWait:
  afterSubmission: 28
  afterReasonsForAppeal: 14
  afterClarifyingQuestionsAnswers: 5

