server:
  port: ${PORT:8093}

management:
  endpoint:
    health:
      show-details: "always"
    status:
      http-mapping:
        UP: 200
        DOWN: 503
  endpoints:
    web:
      base-path: "/"

health:
  services:
    notificationService:
      uri: "https://status.notifications.service.gov.uk"
      response: '"status":"UP"'

spring:
  application:
    name: Immigration & Asylum case notifications API
  jackson.date-format: yyyy-MM-dd
  main:
    allow-bean-definition-overriding: true

govnotify:
  baseUrl: "https://api.notifications.service.gov.uk"
  key: ${IA_GOV_NOTIFY_KEY}
  template:
    appealSubmitted:
      appellant:
        email: 4625616a-178b-45fb-aebf-8cb945369ae0
        sms: 5b7091e5-908a-4c5b-ac66-5dc5216fc53b
      caseOfficer:
        email: 23769f75-673c-4682-8433-d751e540e730
    appealSubmittedOutOfTime:
      appellant:
        email: b864d01f-c80c-4d91-947f-9599f0b64163
        sms: c52f3074-4b5a-47e0-8dec-154ac5fc0513
    requestRespondentEvidenceDirection:
      appellant:
        email: 9c8ab848-b1f7-4dbe-9854-4922e94ece67
        sms: e805b3c5-b1e2-4ad1-9416-3298ca765738
      legalRep:
        email: 33430912-89d5-416d-8d49-52eae9ce82c3
      respondent:
        email: a1fee4a6-6650-4d91-8f9e-cd15944adef4
    respondentEvidenceSubmitted:
      caseOfficer:
        email: b71b11f6-c485-45a2-a162-c2310a094821
    requestReasonsForAppeal:
      appellant:
        email: 50f1b88e-51d5-446c-b2da-1188feb7e26c
        sms: a7056fd8-6de7-408e-881b-c6f9984fe5cf
    submitReasonsForAppeal:
      appellant:
        email: cd10866a-094d-43aa-bdf5-1e20fda9b10d
        sms: d7b0ef96-ea54-46f1-a605-6e3855b09b91
      caseOfficer:
        email: 2e3d6dfb-409d-4b45-a50b-0703c47341ea
    responseReviewDirection:
      legalRep:
        email: e3e36c28-b16a-4e85-b8e1-dbb7f6771181
    buildCaseDirection:
      legalRep:
        email: 13a6331e-b0f5-4e64-ae1b-dc2c2fd0aeeb
    reviewDirection:
      legalRep:
        email: 75c6c191-083d-43a4-8811-f201fc4750a8
      respondent:
        email: a0e0018c-44ef-4a77-a9d5-c036faad29a1
    nonStandardDirection:
      respondent:
        email: 2e0dd0af-12d2-4a37-9bd1-dabdda1959bf
      legalRep:
        email: d85587f4-2a7d-44a2-b6d8-538b91b7144b
    nonStandardDirectionOfHomeOffice:
      legalRep:
        email: a03720df-2c7d-403d-9a45-a58c192e8570
    hearingRequirementsDirection:
      legalRep:
        email: e6694559-38be-46a5-9894-9498b047e2c6
    submitCase:
      caseOfficer:
        email: f6c5ad6b-d585-4421-a93f-c36126f3c4ce
    caseListed:
      caseOfficer:
        email: 58eab057-b5c0-4a69-8f71-a21d6f02da3d
      homeOffice:
        email: 86936ac9-e8d0-4a4c-8169-0948d7fb7935
      legalRep:
        email: b87a1e5b-eec7-4268-a326-059893ab5c28
    caseEdited:
      caseOfficer:
        email: 3ee36e48-b824-4d80-8642-2332eeaab11b
      legalRep:
        email: 20f96361-e43a-4791-ac84-4f61f7e9ba40
      homeOffice:
        email: 56d6f2ac-60a1-4789-94f0-fa02354e205c
    caseEditedNoChange:
      legalRep:
        email: febcbbd2-da42-49b9-b1f9-5ab19e4fc265
      homeOffice:
        email: 1cee9f09-ade4-4b8f-8bc7-8d1fbc3e8089
    appealOutcomeAllowed:
      homeOffice:
        email: ba4f360b-586b-433d-b5c2-ceb0f2f5a323
      legalRep:
        email: 95fa02b7-babb-444d-805c-06dff42cfea7
    appealOutcomeDismissed:
      homeOffice:
        email: ac808545-4e6f-4e87-975b-14d10a929233
      legalRep:
        email: 811b5eba-b53d-4fa1-baa0-5f9f3d1ba68f
    endAppeal:
      legalRep:
        email: 44ae9e7a-adeb-4d78-b2ed-219f4390b166
      homeOffice:
        email: 993c1294-c6b8-4b46-ab0f-ab01b4f6607b
    recordRefusedApplication:
      legalRep:
        email: 46778cba-1db5-4f17-9437-3b2944274df2
      homeOffice:
        email: 911d4121-1300-4c52-b8b3-bfa7526ca74d
    requestCaseBuilding:
      legalRep:
        email: ea1a6d4c-0d6e-4d95-afb7-07ddcebaecbd
    homeOfficeResponseUploaded:
      caseOfficer:
        email: 32584965-8374-469a-a71b-b417da7709ed
    hearingBundleReady:
      legalRep:
        email: 03d427d1-f032-40cb-8e8e-96ea54c2f234
      homeOffice:
        email: d4c6352d-325a-4933-91bb-61eb56554efc
    requestHearingRequirements:
      legalRep:
        email: f6185789-8328-4208-8ee5-8a12d641180f
    reviewHearingRequirements:
      adminOfficer:
        email: 58632d37-fe36-4fae-adfd-b44bf8509770
    withoutHearingRequirements:
      adminOfficer:
        email: 435ea40a-47ac-4397-9bd8-37be50589162
    submittedHearingRequirements:
      legalRep:
        email: bfee0880-9bdd-41a1-805a-8be4818bbb6a
      caseOfficer:
        email: aa36afd2-254b-4fd7-b7c8-72078176294f
    uploadedAdditionalEvidence:
      legalRep:
        email: b012e823-c658-4d10-a7a5-95e54f73dba8
      caseOfficer:
        email: b012e823-c658-4d10-a7a5-95e54f73dba8
      homeOffice:
        email: b012e823-c658-4d10-a7a5-95e54f73dba8
    uploadedAddendumEvidence:
      legalRep:
        email: 271ae717-cbc4-4c6e-8011-cd8c6b1ba0b9
      caseOfficer:
        email: 271ae717-cbc4-4c6e-8011-cd8c6b1ba0b9
      homeOffice:
        email: 271ae717-cbc4-4c6e-8011-cd8c6b1ba0b9
    changeDirectionDueDate:
      legalRep:
        email: 0b7cbe04-1b76-4d17-a854-4071fa3c1d69
      respondent:
        email: 0b7cbe04-1b76-4d17-a854-4071fa3c1d69
    changeDirectionDueDateOfHomeOffice:
      legalRep:
        email: dd2474ca-8b5d-4f2b-9515-37f3bb506e7b
    changeToHearingRequirements:
      adminOfficer:
        email: 6e32ccba-3c68-4b7a-a976-96c149492661
    removeAppealFromOnlineBeforeListing:
      homeOffice:
        email: 0a9b00d5-55d1-469c-8479-c1a2df3fce6d
      legalRep:
        email: 443044b9-3c96-4e62-824a-7f7294e53661
    removeAppealFromOnlineAfterListing:
      homeOffice:
        email: 0845c427-387e-4587-a923-6114c60c7b5d
      legalRep:
        email: b22bac31-7d04-4ad0-a8b3-12ebeb381c9b
    changeHearingCentre:
      legalRep:
        email: 4959d7cc-54f0-4cb4-b386-49940b89925e
      caseOfficer:
        email: 122b7fce-23c9-4b34-9055-8329264fd757
    applyForFtpa:
      respondent:
        email: 01181186-e2d9-44e0-aa35-5ef5aeca0a0f
      appellant:
        email: 16ddedb7-c4e3-481e-bbca-bb99b84ba4a5
      adminOfficer:
        email: 1b5a3d80-b637-4cb7-83ba-a662aaecd3ab
      other:
        email: 9a93d07a-8f0e-4057-9b5d-3f567f2c5fb9


notificationSender.deduplicateSendsWithinSeconds: 60

iaExUiFrontendUrl: ${IA_EXUI_FRONTEND_URL:http://localhost:3002/}
iaAipFrontendUrl: ${IA_AIP_FRONTEND_URL:https://localhost:3000/}

tsvStringsFileLocation: strings.tsv

ia_system_user: ${IA_SYSTEM_USERNAME:system-user}
ia_system_user_password: ${IA_SYSTEM_PASSWORD:system-password}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
  authorisedServices:
    - "ccd"
    - "ccd_data"
    - "ccd_gw"
    - "ccd_ps"
    - "iac"
  authorisedRoles:
    - "caseworker-ia"
    - "citizen"
  roleEventAccess:
    citizen:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
      - "submitReasonsForAppeal"
    caseworker-ia-legalrep-solicitor:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
      - "buildCase"
      - "submitCase"
      - "uploadAdditionalEvidence"
      - "draftHearingRequirements"
      - "requestHearingRequirementsFeature"
      - "uploadAddendumEvidenceLegalRep"
      - "applyForFTPAAppellant"
    caseworker-ia-caseofficer:
      - "sendDirection"
      - "changeDirectionDueDate"
      - "requestCaseEdit"
      - "requestHearingRequirements"
      - "reviewHearingRequirements"
      - "listCaseWithoutHearingRequirements"
      - "requestHearingRequirementsFeature"
      - "draftHearingRequirements"
      - "requestRespondentEvidence"
      - "uploadRespondentEvidence"
      - "requestRespondentReview"
      - "addAppealResponse"
      - "createCaseSummary"
      - "generateHearingBundle"
      - "editCaseListing"
      - "endAppeal"
      - "recordApplication"
      - "requestCaseBuilding"
      - "requestResponseReview"
      - "sendDecisionAndReasons"
      - "uploadAddendumEvidence"
      - "requestReasonsForAppeal"
      - "updateHearingAdjustments"
      - "removeAppealFromOnline"
      - "changeHearingCentre"
    caseworker-ia-admofficer:
      - "listCase"
      - "editCaseListing"
      - "sendDecisionAndReasons"
    caseworker-ia-homeofficeapc:
      - "uploadHomeOfficeBundle"
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
    caseworker-ia-homeofficelart:
      - "uploadHomeOfficeAppealResponse"
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
    caseworker-ia-homeofficepou:
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
      - "applyForFTPARespondent"
    caseworker-ia-respondentofficer:
      - "uploadHomeOfficeBundle"
      - "addAppealResponse"
      - "uploadHomeOfficeAppealResponse"
      - "uploadAdditionalEvidenceHomeOffice"
      - "uploadAddendumEvidenceHomeOffice"
      - "applyForFTPARespondent"
    caseworker-ia-iacjudge:
      - "endAppeal"
      - "sendDecisionAndReasons"
      - "changeDirectionDueDate"
      - "sendDirection"

### dependency configuration
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:4501}
auth.idam.client.detailsUri: "/details"
auth.idam.client.id: ${IA_IDAM_CLIENT_ID:ia}
auth.idam.client.secret: ${IA_IDAM_SECRET:something}
auth.idam.client.redirectUri: ${IA_IDAM_REDIRECT_URI:http://localhost}
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
core_case_data_api_url: ${CCD_URL:http://127.0.0.1:4452}
document_management.url: ${DM_URL:http://127.0.0.1:4506}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:ia}
idam.s2s-auth.url: ${S2S_URL:http://127.0.0.1:4502}

### Email addresses
hearingCentreEmailAddresses:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_EMAIL:hc-bradford@example.com}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_EMAIL:hc-manchester@example.com}
  newport: ${IA_HEARING_CENTRE_NEWPORT_EMAIL:hc-newport@example.com}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_EMAIL:hc-taylorhouse@example.com}
  northShields: ${IA_HEARING_CENTRE_NORTH_SHIELDS_EMAIL:hc-north-shields@example.com}
  birmingham: ${IA_HEARING_CENTRE_BIRMINGHAM_EMAIL:hc-birmingham@example.com}
  hattonCross: ${IA_HEARING_CENTRE_HATTON_CROSS_EMAIL:hc-hatton-cross@example.com}
  glasgow: ${IA_HEARING_CENTRE_GLASGOW_EMAIL:hc-glasgow@example.com}

homeOfficeEmailAddresses:
  bradford: ${IA_HOME_OFFICE_BRADFORD_EMAIL:ho-bradford@example.com}
  manchester: ${IA_HOME_OFFICE_MANCHESTER_EMAIL:ho-manchester@example.com}
  newport: ${IA_HOME_OFFICE_NEWPORT_EMAIL:ho-newport@example.com}
  taylorHouse: ${IA_HOME_OFFICE_TAYLOR_HOUSE_EMAIL:ho-taylorhouse@example.com}
  northShields: ${IA_HOME_OFFICE_NORTH_SHIELDS_EMAIL:ho-north-shields@example.com}
  birmingham: ${IA_HOME_OFFICE_BIRMINGHAM_EMAIL:ho-birmingham@example.com}
  hattonCross: ${IA_HOME_OFFICE_HATTON_CROSS_EMAIL:ho-hatton-cross@example.com}
  glasgow: ${IA_HOME_OFFICE_GLASGOW_EMAIL:ho-glasgow@example.com}

hearingCentreTelephoneNumber:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_TELEPHONE:0300 123 1711}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_TELEPHONE:0300 123 1711}
  newport: ${IA_HEARING_CENTRE_NEWPORT_TELEPHONE:0300 123 1711}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_TELEPHONE:0300 123 1711}
  northShields: ${IA_HEARING_CENTRE_NORTH_SHIELDS_TELEPHONE:0300 123 1711}
  birmingham: ${IA_HEARING_CENTRE_BIRMINGHAM_TELEPHONE:0300 123 1711}
  hattonCross: ${IA_HEARING_CENTRE_HATTON_CROSS_TELEPHONE:0300 123 1711}
  glasgow: ${IA_HEARING_CENTRE_GLASGOW_TELEPHONE:0300 123 1711}

endAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_END_APPEAL_EMAIL:ho-end-appeal@example.com}
allowedAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_ALLOWED_APPEAL_EMAIL:ho-allowed-appeal@example.com}
dismissedAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_DISMISSED_APPEAL_EMAIL:ho-dismissed-appeal@example.com}

reviewHearingRequirementsAdminOfficerEmailAddress: ${IA_ADMIN_OFFICER_REVIEW_HEARING_REQUIREMENTS_EMAIL:ao-review@example.com}

respondentEmailAddresses:
  nonStandardDirectionUntilListing: ${IA_RESPONDENT_NON_STANDARD_DIRECTION_UNTIL_LISTING_EMAIL:respondent@example.com}
  respondentEvidenceDirection: ${IA_RESPONDENT_EVIDENCE_DIRECTION_EMAIL:respondent@example.com}
  respondentReviewDirection: ${IA_RESPONDENT_REVIEW_DIRECTION_EMAIL:respondent-lart@example.com}

ftpaSubmitted:
  ctscAdminEmailAddress: ${IA_CTSC_ADMIN_FTPA_SUBMITTED:ctscFtpaSubmitted@example.gov.uk}
  respondentEmailAddress: ${IA_RESPONDENT_FTPA_SUBMITTED:homeOfficeFtpaSubmitted@example.gov.uk}

appellantDaysToWait:
  afterSubmission: 28
  afterReasonsForAppeal: 14

