server:
  port: ${PORT:8093}

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: "/"

spring:
  application:
    name: Immigration & Asylum case notifications API
  jackson.date-format: yyyy-MM-dd
  main:
    allow-bean-definition-overriding: true

govnotify.key: ${IA_GOV_NOTIFY_KEY}
govnotify.template.responseReviewDirection: e3e36c28-b16a-4e85-b8e1-dbb7f6771181
govnotify.template.buildCaseDirection: 13a6331e-b0f5-4e64-ae1b-dc2c2fd0aeeb
govnotify.template.appealSubmittedCaseOfficer: 23769f75-673c-4682-8433-d751e540e730
govnotify.template.respondentEvidenceDirection: a1fee4a6-6650-4d91-8f9e-cd15944adef4
govnotify.template.legalRepresentativeReviewDirection: 75c6c191-083d-43a4-8811-f201fc4750a8
govnotify.template.respondentNonStandardDirection: 2e0dd0af-12d2-4a37-9bd1-dabdda1959bf
govnotify.template.respondentReviewDirection: a0e0018c-44ef-4a77-a9d5-c036faad29a1
govnotify.template.legalRepresentativeHearingRequirementsDirection: e6694559-38be-46a5-9894-9498b047e2c6
govnotify.template.caseOfficerCaseListed: 58eab057-b5c0-4a69-8f71-a21d6f02da3d
govnotify.template.legalRepresentativeCaseListed: b87a1e5b-eec7-4268-a326-059893ab5c28
govnotify.template.homeOfficeCaseListed: 86936ac9-e8d0-4a4c-8169-0948d7fb7935
govnotify.template.caseOfficerCaseEdited: 1e29cb57-b5ae-4cc1-b51b-093f6ce2a2f2
govnotify.template.endAppealHomeOfficeTemplateId: 993c1294-c6b8-4b46-ab0f-ab01b4f6607b
govnotify.template.endAppealLegalRepresentativeTemplateId: 44ae9e7a-adeb-4d78-b2ed-219f4390b166
govnotify.template.recordRefusedApplicationLegalRepresentativeTemplateId: 46778cba-1db5-4f17-9437-3b2944274df2
govnotify.template.recordRefusedApplicationHomeOfficeTemplateId: 911d4121-1300-4c52-b8b3-bfa7526ca74d
govnotify.template.respondentEvidenceSubmittedTemplateId: b71b11f6-c485-45a2-a162-c2310a094821
govnotify.template.legalRepresentativeBuildCaseDirection: ea1a6d4c-0d6e-4d95-afb7-07ddcebaecbd
govnotify.template.homeOfficeResponseUploadedTemplateId: 32584965-8374-469a-a71b-b417da7709ed

govnotify.baseUrl: "https://api.notifications.service.gov.uk"

hearingCentreEmailAddresses:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_EMAIL:TCWBradfordIA@example.com}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_EMAIL:manchester@example.com}
  newport: ${IA_HEARING_CENTRE_NEWPORT_EMAIL:TCO.NewportIAC@example.com}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_EMAIL:taylorHouse@example.com}

homeOfficeEmailAddresses:
  bradford: ${IA_HOME_OFFICE_BRADFORD_EMAIL:ReformpbAPC@example.com}
  manchester: ${IA_HOME_OFFICE_MANCHESTER_EMAIL:ReformpbManchester@example.com}
  newport: ${IA_HOME_OFFICE_NEWPORT_EMAIL:ReformpbAPC@example.com}
  taylorHouse: ${IA_HOME_OFFICE_TAYLOR_HOUSE_EMAIL:ReformpbCentral@example.com}

hearingCentreTelephoneNumber:
  bradford: ${IA_HEARING_CENTRE_BRADFORD_TELEPHONE:0300 123 1711}
  manchester: ${IA_HEARING_CENTRE_MANCHESTER_TELEPHONE:0300 123 1711}
  newport: ${IA_HEARING_CENTRE_NEWPORT_TELEPHONE:0300 123 1711}
  taylorHouse: ${IA_HEARING_CENTRE_TAYLOR_HOUSE_TELEPHONE:0300 123 1711}

endAppealHomeOfficeEmailAddress: ${IA_HOME_OFFICE_END_APPEAL_EMAIL:ReformpbAPC@example.com}

respondentEmailAddresses:
  nonStandardDirectionUntilListing: ${IA_RESPONDENT_NON_STANDARD_DIRECTION_UNTIL_LISTING_EMAIL}
  respondentEvidenceDirection: ${IA_RESPONDENT_EVIDENCE_DIRECTION_EMAIL}
  respondentReviewDirection: ${IA_RESPONDENT_REVIEW_DIRECTION_EMAIL}

notificationSender.deduplicateSendsWithinSeconds: 60
iaCcdFrontendUrl: ${IA_CCD_FRONTEND_URL:http://localhost:3451/}

tsvStringsFileLocation: strings.tsv

ia_system_user: ${IA_SYSTEM_USERNAME:system-user}
ia_system_user_password: ${IA_SYSTEM_PASSWORD:system-password}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
  authorisedServices:
    - "ccd"
    - "ccd_data"
    - "ccd_gw"
    - "ccd_ps"
    - "iac"
  authorisedRoles:
    - "caseworker-ia"
  roleEventAccess:
    caseworker-ia-legalrep-solicitor:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
      - "buildCase"
      - "submitCase"
      - "uploadAdditionalEvidence"
    caseworker-ia-caseofficer:
      - "sendDirection"
      - "changeDirectionDueDate"
      - "requestCaseEdit"
      - "requestHearingRequirements"
      - "requestRespondentEvidence"
      - "uploadRespondentEvidence"
      - "requestRespondentReview"
      - "addAppealResponse"
      - "createCaseSummary"
      - "generateHearingBundle"
      - "editCaseListing"
      - "endAppeal"
      - "recordApplication"
      - "requestCaseBuilding"
      - "requestResponseReview"
    caseworker-ia-admofficer:
      - "listCase"
      - "editCaseListing"
    caseworker-ia-homeofficeapc:
      - "uploadHomeOfficeBundle"
    caseworker-ia-homeofficelart:
      - "uploadHomeOfficeAppealResponse"
    caseworker-ia-respondentofficer:
      - "uploadHomeOfficeBundle"
      - "addAppealResponse"
      - "uploadHomeOfficeAppealResponse"

### dependency configuration
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:4501}
auth.idam.client.detailsUri: "/details"
auth.idam.client.id: ${IA_IDAM_CLIENT_ID:ia}
auth.idam.client.secret: ${IA_IDAM_SECRET:something}
auth.idam.client.redirectUri: ${IA_IDAM_REDIRECT_URI:http://localhost}
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
core_case_data_api_url: ${CCD_URL:http://127.0.0.1:4452}
document_management.url: ${DM_URL:http://127.0.0.1:4506}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:ia}
idam.s2s-auth.url: ${S2S_URL:http://127.0.0.1:4502}
