apiVersion: v2
name: ia-case-notifications-api
home: https://github.com/hmcts/ia-case-notifications-api
version: 0.0.53
description: Immigration & Asylum Case Notifications Service
maintainers:
  - name: HMCTS Immigration & Asylum Team
    email: ImmigrationandAsylum@HMCTS.NET
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
