java:
  image: 'https://hmctspublic.azurecr.io/ia/case-notifications-api:latest'
  ingressHost: ia-case-notifications-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 8093
  aadIdentityName: ia
  environment:
    IA_EXUI_FRONTEND_URL: https://manage-case.platform.hmcts.net/
    IA_AIP_FRONTEND_URL: https://www.appeal-immigration-asylum-decision.service.gov.uk/
    IA_IDAM_REDIRECT_URI: "https://ia-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    DM_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GW_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_HOME_OFFICE_GOV_NOTIFY_ENABLED: "true"
    IA_DET_PRISON_EMAIL_MAPPINGS: '{
      "prisonEmailMappings": {
        "Addiewell": "det-prison-addiewell@example.com",
        "Albany": "det-prison-albany@example.com",
        "Altcourse": "det-prison-altcourse@example.com",
        "Ashfield": "det-prison-ashfield@example.com",
        "Ashwell": "det-prison-ashwell@example.com",
        "Askham Grange": "det-prison-askham-grange@example.com",
        "Aylesbury": "det-prison-aylesbury@example.com",
        "Barlinnie": "det-prison-barlinnie@example.com",
        "Bedford": "det-prison-bedford@example.com",
        "Bella Centre": "det-prison-bella-centre@example.com",
        "Belmarsh": "det-prison-belmarsh@example.com",
        "Berwyn": "det-prison-berwyn@example.com",
        "Birmingham": "det-prison-birmingham@example.com",
        "Blakenhurst": "det-prison-blakenhurst@example.com",
        "Blantyre House": "det-prison-blantyre-house@example.com",
        "Blundeston": "det-prison-blundeston@example.com",
        "Brinsford": "det-prison-brinsford@example.com",
        "Bristol": "det-prison-bristol@example.com",
        "Brixton": "det-prison-brixton@example.com",
        "Brockhill": "det-prison-brockhill@example.com",
        "Bronzefield": "det-prison-bronzefield@example.com",
        "Buckley Hall": "det-prison-buckley-hall@example.com",
        "Bullingdon": "det-prison-bullingdon@example.com",
        "Bullwood Hall": "det-prison-bullwood-hall@example.com",
        "Bure": "det-prison-bure@example.com",
        "Camp Hill": "det-prison-camp-hill@example.com",
        "Canterbury": "det-prison-canterbury@example.com",
        "Cardiff": "det-prison-cardiff@example.com",
        "Castington": "det-prison-castington@example.com",
        "Castle Huntly": "det-prison-castle-huntly@example.com",
        "Channings Wood": "det-prison-channings-wood@example.com",
        "Chelmsford": "det-prison-chelmsford@example.com",
        "Coldingley": "det-prison-coldingley@example.com",
        "Cookham Wood": "det-prison-cookham-wood@example.com",
        "Cornton Vale": "det-prison-cornton-vale@example.com",
        "Dartmoor": "det-prison-dartmoor@example.com",
        "Deerbolt": "det-prison-deerbolt@example.com",
        "Doncaster": "det-prison-doncaster@example.com",
        "Dorchester": "det-prison-dorchester@example.com",
        "Dovegate": "det-prison-dovegate@example.com",
        "Downview": "det-prison-downview@example.com",
        "Drake Hall": "det-prison-drake-hall@example.com",
        "Dumfries": "det-prison-dumfries@example.com",
        "Durham": "det-prison-durham@example.com",
        "East Sutton Park": "det-prison-east-sutton-park@example.com",
        "Eastwood Park": "det-prison-eastwood-park@example.com",
        "Edinburgh, Saughton": "det-prison-edinburgh-saughton@example.com",
        "Edmunds Hill": "det-prison-edmunds-hill@example.com",
        "Elmley": "det-prison-elmley@example.com",
        "Erlestoke": "det-prison-erlestoke@example.com",
        "Everthorpe": "det-prison-everthorpe@example.com",
        "Exeter": "det-prison-exeter@example.com",
        "Featherstone": "det-prison-featherstone@example.com",
        "Feltham": "det-prison-feltham@example.com",
        "Five Wells": "det-prison-five-wells@example.com",
        "Ford": "det-prison-ford@example.com",
        "Forest Bank": "det-prison-forest-bank@example.com",
        "Foston Hall": "det-prison-foston-hall@example.com",
        "Fosse Way": "det-prison-fosse-way@example.com",
        "Frankland": "det-prison-frankland@example.com",
        "Full Sutton": "det-prison-full-sutton@example.com",
        "Garth": "det-prison-garth@example.com",
        "Gartree": "det-prison-gartree@example.com",
        "Glen Parva": "det-prison-glen-parva@example.com",
        "Glenochil": "det-prison-glenochil@example.com",
        "Gloucester": "det-prison-gloucester@example.com",
        "Grampian": "det-prison-grampian@example.com",
        "Greenock": "det-prison-greenock@example.com",
        "Grendon/Spring Hill": "det-prison-grendon-spring-hill@example.com",
        "Guys Marsh": "det-prison-guys-marsh@example.com",
        "Hatfield (Main site)": "det-prison-hatfield-main@example.com",
        "Hatfield (Lakes site)": "det-prison-hatfield-lakes@example.com",
        "Haverigg": "det-prison-haverigg@example.com",
        "Hewell Grange": "det-prison-hewell-grange@example.com",
        "High Down": "det-prison-high-down@example.com",
        "Highpoint": "det-prison-highpoint@example.com",
        "Hindley": "det-prison-hindley@example.com",
        "Hollesley Bay/Hmyoi Warren Hill": "det-prison-hollesley-bay-warren-hill@example.com",
        "Holloway": "det-prison-holloway@example.com",
        "Holme House": "det-prison-holme-house@example.com",
        "Hull": "det-prison-hull@example.com",
        "Humber": "det-prison-humber@example.com",
        "Huntercombe": "det-prison-huntercombe@example.com",
        "Hydebank Wood": "det-prison-hydebank-wood@example.com",
        "Inverness": "det-prison-inverness@example.com",
        "Isis": "det-prison-isis@example.com",
        "Isle of Wight": "det-prison-isle-of-wight@example.com",
        "Kennet": "det-prison-kennet@example.com",
        "Kilmarnock": "det-prison-kilmarnock@example.com",
        "Kingston": "det-prison-kingston@example.com",
        "Kirkham": "det-prison-kirkham@example.com",
        "Kirklevington Grange": "det-prison-kirklevington-grange@example.com",
        "Lancaster": "det-prison-lancaster@example.com",
        "Lancaster Farms": "det-prison-lancaster-farms@example.com",
        "Latchmere House": "det-prison-latchmere-house@example.com",
        "Leeds": "det-prison-leeds@example.com",
        "Leicester": "det-prison-leicester@example.com",
        "Lewes": "det-prison-lewes@example.com",
        "Leyhill": "det-prison-leyhill@example.com",
        "Lilias Centre": "det-prison-lilias-centre@example.com",
        "Lincoln": "det-prison-lincoln@example.com",
        "Lindholme": "det-prison-lindholme@example.com",
        "Littlehey": "det-prison-littlehey@example.com",
        "Liverpool": "det-prison-liverpool@example.com",
        "Long Lartin": "det-prison-long-lartin@example.com",
        "Low Moss": "det-prison-low-moss@example.com",
        "Low Newton": "det-prison-low-newton@example.com",
        "Lowdham Grange": "det-prison-lowdham-grange@example.com",
        "Magilligan": "det-prison-magilligan@example.com",
        "Maghaberry": "det-prison-maghaberry@example.com",
        "Maidstone": "det-prison-maidstone@example.com",
        "Manchester": "det-prison-manchester@example.com",
        "Moorland Closed": "det-prison-moorland-closed@example.com",
        "Moorland Open": "det-prison-moorland-open@example.com",
        "Morton Hall": "det-prison-morton-hall@example.com",
        "New Hall": "det-prison-new-hall@example.com",
        "North Sea Camp": "det-prison-north-sea-camp@example.com",
        "Northallerton": "det-prison-northallerton@example.com",
        "Northumberland": "det-prison-northumberland@example.com",
        "Norwich": "det-prison-norwich@example.com",
        "Nottingham": "det-prison-nottingham@example.com",
        "Oakwood": "det-prison-oakwood@example.com",
        "Onley": "det-prison-onley@example.com",
        "Parc": "det-prison-parc@example.com",
        "Parkhurst": "det-prison-parkhurst@example.com",
        "Pentonville": "det-prison-pentonville@example.com",
        "Perth": "det-prison-perth@example.com",
        "Peterborough": "det-prison-peterborough@example.com",
        "Polmont": "det-prison-polmont@example.com",
        "Portland": "det-prison-portland@example.com",
        "Prescoed": "det-prison-prescoed@example.com",
        "Preston": "det-prison-preston@example.com",
        "Ranby": "det-prison-ranby@example.com",
        "Reading": "det-prison-reading@example.com",
        "Risley": "det-prison-risley@example.com",
        "Rochester": "det-prison-rochester@example.com",
        "Rye Hill": "det-prison-rye-hill@example.com",
        "Send": "det-prison-send@example.com",
        "Shepton Mallet": "det-prison-shepton-mallet@example.com",
        "Shotts": "det-prison-shotts@example.com",
        "Shrewsbury": "det-prison-shrewsbury@example.com",
        "Spring Hill": "det-prison-spring-hill@example.com",
        "Stafford": "det-prison-stafford@example.com",
        "Standford Hill": "det-prison-standford-hill@example.com",
        "Stocken": "det-prison-stocken@example.com",
        "Stoke Heath": "det-prison-stoke-heath@example.com",
        "Stirling": "det-prison-stirling@example.com",
        "Styal": "det-prison-styal@example.com",
        "Sudbury": "det-prison-sudbury@example.com",
        "Swaleside": "det-prison-swaleside@example.com",
        "Swansea": "det-prison-swansea@example.com",
        "Swinfen Hall": "det-prison-swinfen-hall@example.com",
        "Thameside": "det-prison-thameside@example.com",
        "The Mount": "det-prison-the-mount@example.com",
        "The Verne": "det-prison-the-verne@example.com",
        "The Weare": "det-prison-the-weare@example.com",
        "Thorn Cross": "det-prison-thorn-cross@example.com",
        "Usk": "det-prison-usk@example.com",
        "Wakefield": "det-prison-wakefield@example.com",
        "Wandsworth": "det-prison-wandsworth@example.com",
        "Warren Hill": "det-prison-warren-hill@example.com",
        "Wayland": "det-prison-wayland@example.com",
        "Wealstun": "det-prison-wealstun@example.com",
        "Wellingborough": "det-prison-wellingborough@example.com",
        "Werrington": "det-prison-werrington@example.com",
        "Wetherby": "det-prison-wetherby@example.com",
        "Whatton": "det-prison-whatton@example.com",
        "Whitemoor": "det-prison-whitemoor@example.com",
        "Winchester": "det-prison-winchester@example.com",
        "Wolds": "det-prison-wolds@example.com",
        "Woodhill": "det-prison-woodhill@example.com",
        "Wormwood Scrubs": "det-prison-wormwood-scrubs@example.com",
        "Wymott": "det-prison-wymott@example.com"
      }
    }'

  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - name: ia-gov-notify-key
          alias: IA_GOV_NOTIFY_KEY
        - name: ia-bail-gov-notify-key
          alias: IA_BAIL_GOV_NOTIFY_KEY
        - name: admin-office-newport-email
          alias: IA_ADMIN_NEWPORT_EMAIL
        - name: admin-office-taylor-house-email
          alias: IA_ADMIN_TAYLOR_HOUSE_EMAIL
        - name: admin-office-hatton-cross-email
          alias: IA_ADMIN_HATTON_CROSS_EMAIL
        - name: admin-office-manchester-email
          alias: IA_ADMIN_MANCHESTER_EMAIL
        - name: admin-office-glasgow-email
          alias: IA_ADMIN_GLASGOW_EMAIL
        - name: admin-office-bradford-email
          alias: IA_ADMIN_BRADFORD_EMAIL
        - name: admin-office-birmingham-email
          alias: IA_ADMIN_BIRMINGHAM_EMAIL
        - name: admin-office-harmondsworth-email
          alias: IA_ADMIN_HARMONDSWORTH_EMAIL
        - name: admin-office-yarlswood-email
          alias: IA_ADMIN_YARLSWOOD_EMAIL
        - name: hearing-centre-bradford-email
          alias: IA_HEARING_CENTRE_BRADFORD_EMAIL
        - name: hearing-centre-manchester-email
          alias: IA_HEARING_CENTRE_MANCHESTER_EMAIL
        - name: hearing-centre-newport-email
          alias: IA_HEARING_CENTRE_NEWPORT_EMAIL
        - name: hearing-centre-taylor-house-email
          alias: IA_HEARING_CENTRE_TAYLOR_HOUSE_EMAIL
        - name: hearing-centre-north-shields-email
          alias: IA_HEARING_CENTRE_NORTH_SHIELDS_EMAIL
        - name: hearing-centre-birmingham-email
          alias: IA_HEARING_CENTRE_BIRMINGHAM_EMAIL
        - name: hearing-centre-hatton-cross-email
          alias: IA_HEARING_CENTRE_HATTON_CROSS_EMAIL
        - name: hearing-centre-glasgow-email
          alias: IA_HEARING_CENTRE_GLASGOW_EMAIL
        - name: home-office-bradford-email
          alias: IA_HOME_OFFICE_BRADFORD_EMAIL
        - name: home-office-manchester-email
          alias: IA_HOME_OFFICE_MANCHESTER_EMAIL
        - name: home-office-newport-email
          alias: IA_HOME_OFFICE_NEWPORT_EMAIL
        - name: home-office-taylor-house-email
          alias: IA_HOME_OFFICE_TAYLOR_HOUSE_EMAIL
        - name: home-office-north-shields-email
          alias: IA_HOME_OFFICE_NORTH_SHIELDS_EMAIL
        - name: home-office-birmingham-email
          alias: IA_HOME_OFFICE_BIRMINGHAM_EMAIL
        - name: home-office-hatton-cross-email
          alias: IA_HOME_OFFICE_HATTON_CROSS_EMAIL
        - name: home-office-glasgow-email
          alias: IA_HOME_OFFICE_GLASGOW_EMAIL
        - name: home-office-apc-email
          alias: IA_HOME_OFFICE_APC_EMAIL
        - name: ftpa-home-office-bradford-email
          alias: IA_FTPA_HOME_OFFICE_BRADFORD_EMAIL
        - name: ftpa-home-office-taylor-house-email
          alias: IA_FTPA_HOME_OFFICE_TAYLOR_HOUSE_EMAIL
        - name: ftpa-home-office-north-shields-email
          alias: IA_FTPA_HOME_OFFICE_NEWCASTLE_EMAIL
        - name: ftpa-home-office-hatton-cross-email
          alias: IA_FTPA_HOME_OFFICE_HATTON_CROSS_EMAIL
        - name: ftpa-home-office-yarlswood-email
          alias: IA_FTPA_HOME_OFFICE_YARLSWOOD_EMAIL
        - name: hearing-centre-bradford-telephone
          alias: IA_HEARING_CENTRE_BRADFORD_TELEPHONE
        - name: hearing-centre-manchester-telephone
          alias: IA_HEARING_CENTRE_MANCHESTER_TELEPHONE
        - name: hearing-centre-newport-telephone
          alias: IA_HEARING_CENTRE_NEWPORT_TELEPHONE
        - name: hearing-centre-taylor-house-telephone
          alias: IA_HEARING_CENTRE_TAYLOR_HOUSE_TELEPHONE
        - name: hearing-centre-north-shields-telephone
          alias: IA_HEARING_CENTRE_NORTH_SHIELDS_TELEPHONE
        - name: hearing-centre-birmingham-telephone
          alias: IA_HEARING_CENTRE_BIRMINGHAM_TELEPHONE
        - name: hearing-centre-hatton-cross-telephone
          alias: IA_HEARING_CENTRE_HATTON_CROSS_TELEPHONE
        - name: hearing-centre-glasgow-telephone
          alias: IA_HEARING_CENTRE_GLASGOW_TELEPHONE
        - name: respondent-evidence-direction-email
          alias: IA_RESPONDENT_EVIDENCE_DIRECTION_EMAIL
        - name: respondent-review-direction-email
          alias: IA_RESPONDENT_REVIEW_DIRECTION_EMAIL
        - name: respondent-non-standard-direction-until-listing-email
          alias: IA_RESPONDENT_NON_STANDARD_DIRECTION_UNTIL_LISTING_EMAIL
        - name: home-office-end-appeal-email
          alias: IA_HOME_OFFICE_END_APPEAL_EMAIL
        - name: home-office-allowed-appeal-email
          alias: IA_HOME_OFFICE_ALLOWED_APPEAL_EMAIL
        - name: home-office-dismissed-appeal-email
          alias: IA_HOME_OFFICE_DISMISSED_APPEAL_EMAIL
        - name: admin-officer-review-hearing-requirements-email
          alias: IA_ADMIN_OFFICER_REVIEW_HEARING_REQUIREMENTS_EMAIL
        - name: case-officer-list-case-email
          alias: IA_CASE_OFFICER_LIST_CASE_EMAIL
        - name: ctsc-admin-ftpa-decision-email
          alias: IA_CTSC_ADMIN_FTPA_DECISION
        - name: ctsc-admin-ftpa-submitted-email
          alias: IA_CTSC_ADMIN_FTPA_SUBMITTED
        - name: respondent-ftpa-submitted-email
          alias: IA_RESPONDENT_FTPA_SUBMITTED
        - name: customer-services-telephone
          alias: IA_CUSTOMER_SERVICES_TELEPHONE
        - name: customer-services-email
          alias: IA_CUSTOMER_SERVICES_EMAIL
        - name: system-username
          alias: IA_SYSTEM_USERNAME
        - name: system-password
          alias: IA_SYSTEM_PASSWORD
        - name: idam-client-id
          alias: IA_IDAM_CLIENT_ID
        - name: idam-secret
          alias: IA_IDAM_SECRET
        - name: idam-redirect-uri
          alias: IA_IDAM_REDIRECT_URI
        - name: s2s-secret
          alias: IA_S2S_SECRET
        - name: s2s-microservice
          alias: IA_S2S_MICROSERVICE
        - name: dm-url
          alias: DM_URL
        - name: ccd-url
          alias: CCD_URL
        - name: idam-url
          alias: IDAM_URL
        - name: s2s-url
          alias: S2S_URL
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: fees-admin-officer-email
          alias: FEES_ADMIN_OFFICER_EMAIL
        - name: payment-exceptions-admin-officer-email
          alias: PAYMENT_EXCEPTIONS_ADMIN_OFFICER_EMAIL
        - name: home-office-email-apc
          alias: HOME_OFFICE_EMAIL_APC
        - name: home-office-email-lart
          alias: HOME_OFFICE_EMAIL_LART
        - name: upper-tribunal-notices-email
          alias: IA_UPPER_TRIBUNAL_NOTICES_EMAIL
        - name: utiac-permission-applications-email
          alias: IA_UPPER_TRIBUNAL_PERMISSION_APPLICATIONS_EMAIL
        - name: nbc-email
          alias: IA_NBC_EMAIL
        - name: ctsc-email
          alias: IA_CTSC_EMAIL
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: bail-hearing-centre-bradford-email
          alias: IA_BAIL_HEARING_CENTRE_BRADFORD_EMAIL
        - name: bail-hearing-centre-birmingham-email
          alias: IA_BAIL_HEARING_CENTRE_BIRMINGHAM_EMAIL
        - name: bail-hearing-centre-newport-email
          alias: IA_BAIL_HEARING_CENTRE_NEWPORT_EMAIL
        - name: bail-hearing-centre-taylor-house-email
          alias: IA_BAIL_HEARING_CENTRE_TAYLOR_HOUSE_EMAIL
        - name: bail-hearing-centre-hatton-cross-email
          alias: IA_BAIL_HEARING_CENTRE_HATTON_CROSS_EMAIL
        - name: bail-hearing-centre-manchester-email
          alias: IA_BAIL_HEARING_CENTRE_MANCHESTER_EMAIL
        - name: bail-hearing-centre-glasgow-email
          alias: IA_BAIL_HEARING_CENTRE_GLASGOW_EMAIL
        - name: bail-hearing-centre-yarlswood-email
          alias: IA_BAIL_HEARING_CENTRE_YARLSWOOD_EMAIL
        - name: bail-home-office-email
          alias: IA_BAIL_HOME_OFFICE_EMAIL
        - name: bail-test-applicant-mobile
          alias: IA_TEST_APPLICANT_MOBILE
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: ia-config-validator-secret
          alias: IA_CONFIG_VALIDATOR_SECRET
        - name: bail-upper-tribunal-email
          alias: IA_BAIL_UPPER_TRIBUNAL_EMAIL
        - name: home-office-apply-for-costs-email
          alias: HO_APPLY_FOR_COSTS_EMAIL
        - name: ia-det-prison-email-mappings
          alias: IA_DET_PRISON_EMAIL_MAPPINGS
