govnotify.key: not-used-in-integration
govnotify.bail.key: not-used-in-integration

respondentEmailAddresses:
  nonStandardDirectionUntilListing: not-used-in-integration
  respondentEvidenceDirection: not-used-in-integration
  respondentReviewDirection: not-used-in-integration

apcPrivateHomeOfficeEmailAddress: not-used-in-integration
feesAdminOfficerEmailAddress: not-used-in-integration
apcHomeOfficeEmailAddress: not-used-in-integration
lartHomeOfficeEmailAddress: not-used-in-integration
upperTribunalNoticesEmailAddress: not-used-in-integration
nbcEmailAddress: not-used-in-integration
ctscEmailAddress: not-used-in-integration

idam:
  s2s-authorised:
    services: ia
