govnotify.key: not-used-in-integration

respondentEmailAddresses:
  nonStandardDirectionUntilListing: not-used-in-integration
  respondentEvidenceDirection: not-used-in-integration
  respondentReviewDirection: not-used-in-integration

apcPrivateHomeOfficeEmailAddress: not-used-in-integration
feesAdminOfficerEmailAddress: not-used-in-integration

security:
  authorisedServices:
    - "ia"