package uk.gov.hmcts.reform.iacasenotificationsapi.domain.entities.ccd;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;

public enum Event {

    ADD_APPEAL_RESPONSE("addAppealResponse"),
    ADD_EVIDENCE_FOR_COSTS("addEvidenceForCosts"),
    ADJOURN_HEARING_WITHOUT_DATE("adjournHearingWithoutDate"),
    ADA_SUITABILITY_REVIEW("adaSuitabilityReview"),
    APPLY_FOR_COSTS("applyForCosts"),
    APPLY_FOR_FTPA_APPELLANT("applyForFTPAAppellant"),
    APPLY_FOR_FTPA_RESPONDENT("applyForFTPARespondent"),
    ASYNC_STITCHING_COMPLETE("asyncStitchingComplete"),
    BUILD_CASE("buildCase"),
    CASE_LISTING("caseListing"),
    CHANGE_BAIL_DIRECTION_DUE_DATE("changeBailDirectionDueDate"),
    CHANGE_DIRECTION_DUE_DATE("changeDirectionDueDate"),
    CHANGE_HEARING_CENTRE("changeHearingCentre"),
    CONSIDER_MAKING_COSTS_ORDER("considerMakingCostsOrder"),
    CREATE_BAIL_CASE_LINK("createBailCaseLink"),
    CREATE_CASE_LINK("createCaseLink"),
    CREATE_CASE_SUMMARY("createCaseSummary"),
    CUSTOMISE_HEARING_BUNDLE("customiseHearingBundle"),
    DECIDE_AN_APPLICATION("decideAnApplication"),
    DECIDE_COSTS_APPLICATION("decideCostsApplication"),
    DECIDE_FTPA_APPLICATION("decideFtpaApplication"),
    DECISION_WITHOUT_HEARING("decisionWithoutHearing"),
    DRAFT_HEARING_REQUIREMENTS("draftHearingRequirements"),
    EDIT_APPEAL("editAppeal"),
    EDIT_APPEAL_AFTER_SUBMIT("editAppealAfterSubmit"),
    EDIT_BAIL_APPLICATION_AFTER_SUBMIT("editBailApplicationAfterSubmit"),
    EDIT_BAIL_DOCUMENTS("editBailDocuments"),
    EDIT_CASE_LISTING("editCaseListing"),
    EDIT_DOCUMENTS("editDocuments"),
    EDIT_PAYMENT_METHOD("editPaymentMethod"),
    END_APPEAL("endAppeal"),
    END_APPEAL_AUTOMATICALLY("endAppealAutomatically"),
    END_APPLICATION("endApplication"),
    FORCE_CASE_TO_CASE_UNDER_REVIEW("forceCaseToCaseUnderReview"),
    FORCE_CASE_TO_HEARING("forceCaseToHearing"),
    FORCE_CASE_TO_SUBMIT_HEARING_REQUIREMENTS("forceCaseToSubmitHearingRequirements"),
    FORCE_REQUEST_CASE_BUILDING("forceRequestCaseBuilding"),
    GENERATE_HEARING_BUNDLE("generateHearingBundle"),
    LEADERSHIP_JUDGE_FTPA_DECISION("leadershipJudgeFtpaDecision"),
    LINK_APPEAL("linkAppeal"),
    LIST_CASE("listCase"),
    LIST_CASE_WITHOUT_HEARING_REQUIREMENTS("listCaseWithoutHearingRequirements"),
    LIST_CMA("listCma"),
    MAKE_AN_APPLICATION("makeAnApplication"),
    MAKE_NEW_APPLICATION("makeNewApplication"),
    MANAGE_FEE_UPDATE("manageFeeUpdate"),
    MARK_APPEAL_AS_ADA("markAppealAsAda"),
    MARK_APPEAL_AS_DETAINED("markAppealAsDetained"),
    MARK_APPEAL_AS_REMITTED("markAppealAsRemitted"),
    MARK_APPEAL_PAID("markAppealPaid"),
    MARK_AS_READY_FOR_UT_TRANSFER("markAsReadyForUtTransfer"),
    MAINTAIN_BAIL_CASE_LINKS("maintainBailCaseLinks"),
    MAINTAIN_CASE_LINKS("maintainCaseLinks"),
    NOC_REQUEST("nocRequest"),
    NOC_REQUEST_BAIL("nocRequestBail"),
    PAY_AND_SUBMIT_APPEAL("payAndSubmitAppeal"),
    PAY_FOR_APPEAL("payForAppeal"),
    PAYMENT_APPEAL("paymentAppeal"),
    RECORD_APPLICATION("recordApplication"),
    RECORD_OUT_OF_TIME_DECISION("recordOutOfTimeDecision"),
    RECORD_REMISSION_DECISION("recordRemissionDecision"),
    RECORD_THE_DECISION("recordTheDecision"),
    REINSTATE_APPEAL("reinstateAppeal"),
    REMOVE_APPEAL_FROM_ONLINE("removeAppealFromOnline"),
    REMOVE_DETAINED_STATUS("removeDetainedStatus"),
    REMOVE_LEGAL_REPRESENTATIVE("removeLegalRepresentative"),
    REMOVE_REPRESENTATION("removeRepresentation"),
    RESPOND_TO_COSTS("respondToCosts"),
    REQUEST_CASE_BUILDING("requestCaseBuilding"),
    REQUEST_CASE_EDIT("requestCaseEdit"),
    REQUEST_CMA_REQUIREMENTS("requestCmaRequirements"),
    REQUEST_FEE_REMISSION("requestFeeRemission"),
    REQUEST_HEARING_REQUIREMENTS("requestHearingRequirements"),
    REQUEST_HEARING_REQUIREMENTS_FEATURE("requestHearingRequirementsFeature"),
    REQUEST_NEW_HEARING_REQUIREMENTS("requestNewHearingRequirements"),
    REQUEST_REASONS_FOR_APPEAL("requestReasonsForAppeal"),
    REQUEST_RESPONDENT_EVIDENCE("requestRespondentEvidence"),
    REQUEST_RESPONDENT_REVIEW("requestRespondentReview"),
    REQUEST_RESPONSE_AMEND("requestResponseAmend"),
    REQUEST_RESPONSE_REVIEW("requestResponseReview"),
    RESIDENT_JUDGE_FTPA_DECISION("residentJudgeFtpaDecision"),
    RESTORE_STATE_FROM_ADJOURN("restoreStateFromAdjourn"),
    REVERT_STATE_TO_AWAITING_RESPONDENT_EVIDENCE("revertStateToAwaitingRespondentEvidence"),
    REVIEW_HEARING_REQUIREMENTS("reviewHearingRequirements"),
    REVIEW_TIME_EXTENSION("reviewTimeExtension"),
    SEND_BAIL_DIRECTION("sendBailDirection"),
    SEND_DECISION_AND_REASONS("sendDecisionAndReasons"),
    SEND_DIRECTION("sendDirection"),
    SEND_DIRECTION_WITH_QUESTIONS("sendDirectionWithQuestions"),
    SEND_UPLOAD_BAIL_SUMMARY_DIRECTION("sendUploadBailSummaryDirection"),
    START_APPEAL("startAppeal"),
    STOP_LEGAL_REPRESENTING("stopLegalRepresenting"),
    SUBMIT_ADDENDUM_EVIDENCE("submitAddendumEvidence"),
    SUBMIT_ADDENDUM_EVIDENCE_ADMIN_OFFICER("submitAddendumEvidenceAdminOfficer"),
    SUBMIT_ADDENDUM_EVIDENCE_HOME_OFFICE("submitAddendumEvidenceHomeOffice"),
    SUBMIT_ADDENDUM_EVIDENCE_LEGAL_REP("submitAddendumEvidenceLegalRep"),
    SUBMIT_APPEAL("submitAppeal"),
    SUBMIT_APPLICATION("submitApplication"),
    SUBMIT_CASE("submitCase"),
    SUBMIT_CLARIFYING_QUESTION_ANSWERS("submitClarifyingQuestionAnswers"),
    SUBMIT_CMA_REQUIREMENTS("submitCmaRequirements"),
    SUBMIT_REASONS_FOR_APPEAL("submitReasonsForAppeal"),
    SUBMIT_TIME_EXTENSION("submitTimeExtension"),
    TRANSFER_OUT_OF_ADA("transferOutOfAda"),
    TURN_ON_NOTIFICATIONS("turnOnNotifications"),
    UNLINK_APPEAL("unlinkAppeal"),
    UPDATE_DETENTION_LOCATION("updateDetentionLocation"),
    UPDATE_HEARING_ADJUSTMENTS("updateHearingAdjustments"),
    UPDATE_PAYMENT_STATUS("updatePaymentStatus"),
    UPDATE_TRIBUNAL_DECISION("updateTribunalDecision"),
    UPLOAD_ADDENDUM_EVIDENCE("uploadAddendumEvidence"),
    UPLOAD_ADDENDUM_EVIDENCE_ADMIN_OFFICER("uploadAddendumEvidenceAdminOfficer"),
    UPLOAD_ADDENDUM_EVIDENCE_HOME_OFFICE("uploadAddendumEvidenceHomeOffice"),
    UPLOAD_ADDENDUM_EVIDENCE_LEGAL_REP("uploadAddendumEvidenceLegalRep"),
    UPLOAD_ADDITIONAL_EVIDENCE("uploadAdditionalEvidence"),
    UPLOAD_ADDITIONAL_EVIDENCE_HOME_OFFICE("uploadAdditionalEvidenceHomeOffice"),
    UPLOAD_BAIL_SUMMARY("uploadBailSummary"),
    UPLOAD_DOCUMENTS("uploadDocuments"),
    UPLOAD_HOME_OFFICE_APPEAL_RESPONSE("uploadHomeOfficeAppealResponse"),
    UPLOAD_HOME_OFFICE_BUNDLE("uploadHomeOfficeBundle"),
    UPLOAD_RESPONDENT_EVIDENCE("uploadRespondentEvidence"),
    UPLOAD_SIGNED_DECISION_NOTICE("uploadSignedDecisionNotice"),

    @JsonEnumDefaultValue
    UNKNOWN("unknown");

    private final String id;

    Event(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return id;
    }

}
